cart/urls.py
from django.urls import path
from cart.views import (CartTemplateView, CartInfoTemplateView, CartAddFormView,
                        CartChangeFormView, CartRemoveFormView, CheckoutTemplateView)


app_name = 'cart'

urlpatterns = [
    path('', CartTemplateView.as_view(), name='cart'),
    path('info/', CartInfoTemplateView.as_view(), name='info'),
    path('add/', CartAddFormView.as_view(), name='add'),
    path('change/', CartChangeFormView.as_view(), name='change'),
    path('remove/', CartRemoveFormView.as_view(), name='remove'),
    path('checkout/', CheckoutTemplateView.as_view(), name='checkout'),
]

cml/urls.py
from __future__ import absolute_import
from django.conf.urls import re_path, include
from . import views

app_urlpatterns = [
    re_path(r'^1c_exchange.php$', views.front_view, name='front_view'),
    re_path(r'^exchange$', views.front_view, name='front_view'),
]

urlpatterns = [
    re_path(r'^', include((app_urlpatterns, 'cml'), namespace='cml')),
]

myshop3/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include, re_path
import debug_toolbar
import notifications.urls


def robots(request):
    return render(request, 'shop/robots.txt', content_type='text/plain')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('summernote/', include('django_summernote.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('news/', include('info.urls', namespace='news')),
    path('reviews/', include('info.urls', namespace='reviews')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/profile/', include('profiles.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('profiles.accounts_urls')),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('chaining/', include('smart_selects.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)), # Использует debug_toolbar

    re_path(r'^cml/', include('cml.urls')),

    path('robots.txt', robots, name='robots'),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.views.generic import TemplateView

from orders.views import order_create, thanks

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='create_orders'),
    #path('create/thanks/', TemplateView.as_view(template_name='orders/thanks.html'), name='thanks'),
    path('create/thanks/', thanks, name='thanks'),


]

shop/urls.py
from django.urls import path
from .views import (index, catalog, catlist, catlinks,
                    shoplist, productdetails,
                    modalproduct, compareproducts,
                    products_by_brand, search,
                    notify_create,
                    price_list_count,



                    )


app_name = 'shop'

urlpatterns = [
    path('', index, name='index_page'),
    path('category/<int:pk>/sort/brand/', products_by_brand, name='products-all'),
    path('category/<int:pk>/sort/brand/<slug>/', products_by_brand, name='products-by-brand'),
    path('catalog/', catalog, name='catalog'),
    path('catalog/catlist/<slug>/', catlist, name='catlist'),
    path('catlinks/<slug>/', catlinks, name='catlinks'),
    #path('shop/', shop, name='shop'),
    path('shop-list/<slug>/', shoplist, name='shop-list'),
    path('product-details/<str:product_slug>/', productdetails, name='product-details'),
    path('modal-product/<slug>/', modalproduct, name='modal-product'),
    path('compare-products/<category_slug>/', compareproducts, name='compare-products-by-category'),
    path('compare-products/', compareproducts, name='compare-products'),
    path('search/', search, name='search'),
    path('notify_create/', notify_create, name='notify_create'),
    path('price/<pk>/', price_list_count, name='price_list_count'),




]

cart/models.py
from decimal import Decimal

from django.db.models import Sum, F

from shop.models import Product
from django.db import models


class Cart(models.Model):
    products = models.ManyToManyField(Product, through='CartProduct')

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return str(self.id)

    @property
    def full_price(self):
        t = self.cartproduct_set.aggregate(
            total=Sum(
                F('quantity') * F('product__price'),
                output_field=models.DecimalField())
        ).get('total') or Decimal(0)
        return t.quantize(Decimal('0.01'))

    @property
    def discount_price(self):
        t = self.cartproduct_set.aggregate(
            total=Sum(
                F('quantity') * F('product__price') * (100 - F('product__discount')) / 100,
                output_field=models.DecimalField(decimal_places=2))
        ).get('total') or Decimal(0)
        return t.quantize(Decimal('0.01'))

    @property
    def count(self):
        return self.products.count()

    @property
    def count_products(self):
        return self.cartproduct_set.aggregate(
        total=Sum(F('quantity'),
        output_field=models.IntegerField())
    ).get('total')


    @property
    def is_empty(self):
        return not self.count


class CartProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return 'Cart item for product {0}'.format(self.product.title)

    @property
    def full_price(self):
        return Decimal(self.quantity * self.product.price).quantize(Decimal('0.01'))

    @property
    def discount_price(self):
        return Decimal(self.quantity * self.product.get_sale()).quantize(Decimal('0.01'))

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError

from cart.models import CartProduct
from shop.models import Product


class CartBaseProductForm(forms.ModelForm):
    product = forms.CharField()
    quantity = forms.IntegerField(required=False)

    class Meta:
        model = CartProduct
        fields = ('product', 'quantity')

    def __init__(self, *args, **kwargs):
        self.cart = kwargs.pop('cart')
        super().__init__(*args, **kwargs)

    def clean_product(self):
        product_slug = self.cleaned_data.get('product')
        product = Product.objects.filter(slug=product_slug).first()
        if product:
            return product
        raise ValidationError('Product not found!')


class CartAddProductForm(CartBaseProductForm):
    def save(self, commit=True):
        product = self.cleaned_data.get('product')
        quantity = self.cleaned_data.get('quantity') or 1

        cart_product, created = CartProduct.objects.get_or_create(
            cart=self.cart, product=product, defaults={'quantity': quantity}
        )

        if not created:
            cart_product.quantity += quantity
            cart_product.save()


class CartChangeProductForm(CartBaseProductForm):

    def save(self, commit=True):
        product = self.cleaned_data.get('product')
        quantity = self.cleaned_data.get('quantity') or 1
        CartProduct.objects.filter(
            cart=self.cart, product=product
        ).update(quantity=quantity)


class CartRemoveProductForm(CartBaseProductForm):

    class Meta:
        model = CartProduct
        fields = ('product',)

    def save(self, commit=True):
        product = self.cleaned_data.get('product')
        CartProduct.objects.filter(cart=self.cart, product=product).delete()

cart/views.py
from django.http import JsonResponse, HttpResponse
from django.views import View
from django.views.generic import TemplateView, FormView
from easy_thumbnails.alias import aliases
from easy_thumbnails.files import get_thumbnailer

from django.contrib.staticfiles.templatetags.staticfiles import static

from cart.forms import CartAddProductForm, CartChangeProductForm, CartRemoveProductForm


class CartTemplateView(TemplateView):
    template_name = 'cart/cart.html'


class CartInfoTemplateView(View):
    def get(self, request, *args, **kwargs):
        def get_thumb(field, alias=None):
            url = static('shop/img/no-image-70x70.png') # Если картинки нет, отобразить заглушку в корзине.
            if not field:
                return url

            if not alias:
                return field.url

            thumbnail_options = aliases.get(alias)
            thumbnailer = get_thumbnailer(field)
            return thumbnailer.get_thumbnail(thumbnail_options).url

        data = {
            'count': request.cart.count,
            'full_price': request.cart.full_price,
            'discount_price': request.cart.discount_price,
            'count_products': request.cart.count_products,
            'products': [
                {
                    'id': cartproduct.product.id,
                    'url': cartproduct.product.get_absolute_url(),
                    'slug': cartproduct.product.slug,
                    'title': cartproduct.product.title,
                    'images': get_thumb(cartproduct.product.images),
                    'thumb': get_thumb(cartproduct.product.images, 'cart'),
                    'quantity': cartproduct.quantity,
                    'price': cartproduct.product.price,
                    'discount_price': cartproduct.discount_price,
                    'total': cartproduct.full_price,
                    'vendor_code': cartproduct.product.vendor_code
                } for cartproduct in request.cart.cartproduct_set.all()
            ],
        }

        return JsonResponse(data)


class CartFormViewMixin:
    success_status = 201
    error_status = 400

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'cart': self.request.cart})
        return kwargs

    def form_valid(self, form):
        form.save()
        return HttpResponse(status=self.success_status)

    def form_invalid(self, form):
        return JsonResponse(form.errors, status=self.error_status)


class CartAddFormView(CartFormViewMixin, FormView):
    form_class = CartAddProductForm


class CartChangeFormView(CartFormViewMixin, FormView):
    form_class = CartChangeProductForm


class CartRemoveFormView(CartFormViewMixin, FormView):
    form_class = CartRemoveProductForm
    success_status = 204


class CheckoutTemplateView(TemplateView):
    template_name = 'cart/checkout.html'

cart/templates/cart/cart.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load banner %}


{% block title %}
    Корзина
{% endblock %}

{% block content %}
		<!-- START PAGE-CONTENT -->
		<section class="page-content">
			<div class="container">
	            <div class="row">
					<div class="col-md-12">
						<ul class="page-menu">
							<li><a href="/">Главная</a></li>
							<li class="active"><a href="{% url 'cart:cart' %}">Корзина</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						{% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
						{% include 'shop/bestseller.html' %} <!--Подгружаем код из файла shop/bestseller.html -->
					</div>
					<div class="col-md-9">
						<!-- START PRODUCT-BANNER -->
						<div class="product-banner">
							<div class="row">
                                {% center_big_banner %} <!-- Большой баннер 870×216 -->
							</div>
						</div>
						<!-- END PRODUCT-BANNER -->
						<!-- Start Shopping-Cart -->
						<div class="shopping-cart">
							<div class="row">
								<div class="col-md-12">
									<div class="cart-title">
										<h2>Корзина</h2><!-- Для английского шрифта указаьть class="entry-title"  -->
									</div>
									<!-- Start Table -->
                                    <div id="cart-table">

                                    </div>
									<div class="shopping-checkout">
										<a href="{% url 'shop:catalog' %}" class="btn btn-success pull-left">Продолжить покупки</a>
                                        {%  if not request.cart.is_empty %}
                                            <a href="{% url 'cart:checkout' %}" id="btn-checkout" class="btn btn-primary pull-right">Далее</a>
                                        {% endif %}
									</div>
								</div>
							</div>
						</div>
						<!-- End Shopping-Cart -->
					</div>
				</div>
			</div>
        </section>
{% endblock content %}

cart/templates/cart/checkout.html
{% extends 'account/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load banner %}
{% load i18n %}


{% block title %}
    Проверить данные о товаре
{% endblock %}

{#<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>#}

{% block content %}

        <!-- Стили для фокуса в placeholder-->
    <style>
        :focus::-webkit-input-placeholder {color: transparent}
        :focus::-moz-placeholder          {color: transparent}
        :focus:-moz-placeholder           {color: transparent}
        :focus:-ms-input-placeholder      {color: transparent}
    </style>

    <!-- START PAGE-CONTENT -->
		<section class="page-content">
			<div class="container">
	            <div class="row">
					<div class="col-md-12">
						<ul class="page-menu">
							<li><a href="/">Главная</a></li>
							<li><a href="{% url 'cart:cart' %}">Корзина</a></li>
							<li class="active"><a href="{% url 'cart:checkout' %}">Проверить</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						{% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
						{% include 'shop/bestseller.html' %} <!--Подгружаем код из файла shop/bestseller.html -->
					</div>
					<div class="col-md-9">
						<!-- START PRODUCT-BANNER -->
						<div class="product-banner">
							<div class="row">
                                {% center_big_banner %} <!-- Большой баннер 870×216 -->
							</div>
						</div>
						<!-- END PRODUCT-BANNER -->
						<!-- Start checkout-area -->
						<div class="checkout-area">
							<div class="row">
                                {% if request.cart.cartproduct_set.all %}
								<div class="col-md-12">
									<div class="cart-title">
                                        {% if request.user.is_authenticated %}
										<h2>Проверьте Ваш заказ</h2><!-- Для английского шрифта указаьть class="entry-title"  -->
                                            {% else %}
                                            <h2>Вариант оформления заказа</h2><!-- Для английского шрифта указаьть class="entry-title"  -->
                                        {% endif %}
									</div>
									<!-- Accordion start -->
									<div class="panel-group" id="accordion">
                                        {% if not request.user.is_authenticated %}
										<!-- Start 1 Checkout-options -->
										<div class="panel panel_default">
											<div class="panel-heading">
												<h4 class="panel-title">
													<a class="accordion-trigger" data-toggle="collapse" data-parent="#accordion" href="#checkout-options" style="font-weight: inherit;">
                                                        Вариант оформления заказа  <i class="fa fa-caret-down"></i>
                                                    </a>
												</h4>
											</div>
											<div id="checkout-options" class="collapse in">
												<div class="panel-body">
													<div class="row">
														<div class="col-md-6 col-xs-12">
                                                            <div class="checkout-collapse">
                                                                <h3 class="title-group-3 gfont-1">Новый клиен</h3>
                                                                <p>Регистрация нового клиента</p>
                                                                <a href="{% url 'account_signup' %}">
                                                                    <button class="btn btn-primary">Регистрация
                                                                    </button>
                                                                </a>
                                                                    <br><br>
                                                                <p>Создав аккаунт, вы сможете делать покупки
                                                                     быстрее, будете в курсе статуса заказа, сохраняйте
                                                                     и отслеживайте Ваши заказы, которые вы сделали ранее.</p>
                                                                <br><br>
                                                                <a href="{% url 'order:create_orders' %}">
                                                                    <button class="btn btn-primary">Я гость
                                                                    </button>
                                                                </a>
                                                                    <br><br>
                                                                <p>Продолжить как гость</p>
                                                            </div>
														</div>
														<div class="col-md-6 col-xs-12">
															<div class="checkout-collapse">
																<h3 class="title-group-3 gfont-1">Я ваш клиент</h3>
																<p>Я постоянный клиент</p>
                                                                <a href="{% url 'account_login' %}"><button class="btn btn-primary">Авторизоваться</button></a>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
                                        {% endif %}


										<!-- Start 6 Checkout-Confirm -->
                                            <div class="panel panel_default">
                                                <div class="panel-heading">
                                                    <h4 class="panel-title">
                                                        <a class="accordion-trigger" data-toggle="collapse" data-parent="#accordion" href="#checkout-confirm" style="font-weight: inherit;">
                                                            Ваш заказ <i class="fa fa-caret-down"></i>
                                                        </a>
                                                    </h4>
                                                </div>
                                                <div id="checkout-confirm" class="collapse in">
                                                    <div class="panel-body">
                                                        <div class="table-responsive">
                                                            <table class="table table-bordered table-hover bmw">
                                                                <thead>
                                                                    <tr>
                                                                        <td class="text-center">Изображение</td>
                                                                        <td class="text-left">Наименование</td>
                                                                        <td class="text-center">Количество</td>
                                                                        <td class="text-right">Цена</td>
                                                                        <td class="text-right">Всего</td>
                                                                    </tr>
                                                                </thead>
                                                                {% for item in request.cart.cartproduct_set.all %}
                                                                <tbody>
                                                                    <tr>
                                                                        <td class="text-center">
                                                                            {% if item.product.images %}
                                                                            <img class="img-thumbnail" src="{{ item.product.images|thumbnail_url:'cart' }}" alt="{{ item.product.title }}" />
                                                                                {% else %}
                                                                                <img class="img-thumbnail" src="{% static 'shop/img/no-image-70x70.png' %}"/>
                                                                            {% endif %}
                                                                        </td>
                                                                        <td class="text-left">{{ item.product.title }}<br><br><small>Артикул: <span class="text-stock" >{{ item.product.vendor_code }}</span></small></td>
                                                                        <td class="text-center">{{ item.quantity }}</td>
                                                                        <td class="text-right">&#8381; {{ item.product.price }}</td>
                                                                        <td class="text-right">&#8381; {{ item.discount_price }}</td>
                                                                    </tr>
                                                                </tbody>
                                                                {% endfor %}
                                                                <tfoot>
                                                                    <tr>
                                                                        <td class="text-right" colspan="4">
                                                                            <strong>Всего:</strong>
                                                                        </td>
                                                                        <td class="text-right">&#8381; {{ request.cart.discount_price }}</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="text-right" colspan="4">
                                                                            <strong>Количество:</strong>
                                                                        </td>
                                                                        <td class="text-right">{{ request.cart.count_products }} шт.</td>
                                                                    </tr>
                                                                </tfoot>
                                                            </table>
                                                        </div>
                                                        <div class="buttons pull-right">
                                                            {% if request.user.is_authenticated %}
                                                                <a href="{% url 'order:create_orders' %}"><input type="button" class="btn btn-primary" value="Далее" /></a>
                                                            {% endif %}
                                                        </div>
                                                        <div class="buttons pull-left">
                                                            <a href="{% url 'cart:cart' %}"><input type="button" class="btn btn-success" value="Назад в корзину" /></a>
                                                        </div>
                                                    </div>
                                                </div>
                                                {% else %}
                                                <div class="shopping-checkout">
                                                    <h2>Ваша корзина пуста</h2><!-- Для английского шрифта указаьть class="entry-title"  -->
                                                    <a href="{% url 'shop:catalog' %}" class="btn btn-success pull-left">Продолжить покупки</a>
                                                </div>
                                            </div>
										<!-- End Checkout-Confirm -->
									</div>
									<!-- Accordion end -->
								</div>
                                {% endif %}
							</div>
						</div>
						<!-- End Shopping-Cart -->
					</div>
				</div>
			</div>
        </section>
{% endblock content %}
{% comment %}{% endcomment %}