cml/urls.py
from __future__ import absolute_import
from django.conf.urls import re_path, include
from . import views

app_urlpatterns = [
    re_path(r'^1c_exchange.php$', views.front_view, name='front_view'),
    re_path(r'^exchange$', views.front_view, name='front_view'),
]

urlpatterns = [
    re_path(r'^', include((app_urlpatterns, 'cml'), namespace='cml')),
]

contacts/urls.py
from django.urls import path
from contacts.views import contact, about, backcall, delivery

app_name = 'contacts'

urlpatterns = [
    path('', contact, name='contact'),
    path('about/', about, name='about'),
    path('backcall/', backcall, name='backcall'),
    path('delivery/', delivery, name='delivery'),

]

myshop3/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include, re_path
import debug_toolbar
import notifications.urls


def robots(request):
    return render(request, 'shop/robots.txt', content_type='text/plain')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('summernote/', include('django_summernote.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('news/', include('info.urls', namespace='news')),
    path('reviews/', include('info.urls', namespace='reviews')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/profile/', include('profiles.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('profiles.accounts_urls')),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('chaining/', include('smart_selects.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)), # Использует debug_toolbar

    re_path(r'^cml/', include('cml.urls')),

    path('robots.txt', robots, name='robots'),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models


class Contacts(models.Model):
    '''Форма обратной связи'''
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    phone = models.CharField(max_length=100, blank=True, verbose_name='Телефон')
    email = models.EmailField(max_length=100, blank=True, verbose_name='email')
    text = models.TextField(max_length=1500, verbose_name='Сообщение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['-created']

    def __str__(self):
        return self.full_name


class Maps(models.Model):
    '''Вставка ссылки на карту панораму'''
    name = models.CharField(max_length=250, verbose_name='Название')
    maps = models.URLField(max_length=1000, verbose_name='Ссылка')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Карта'
        verbose_name_plural = 'Карты'
        ordering = ['-created']

    def __str__(self):
        return self.name


class Address(models.Model):
    '''Контактные данные магазина'''
    title = models.CharField(max_length=150, blank=True, verbose_name='Заголовок')
    email_one = models.EmailField(max_length=100, blank=True, verbose_name='Email-1')
    email_two = models.EmailField(max_length=100, blank=True, verbose_name='Email-2')
    website = models.URLField(max_length=150, blank=True, verbose_name='Сайт')
    phone_one = models.CharField(max_length=100, blank=True, verbose_name='Телефон-1')
    phone_two = models.CharField(max_length=100, blank=True, verbose_name='Телефон-2')
    address = models.CharField(max_length=150, blank=True, verbose_name='Адрес')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'
        ordering = ['-created']

    def __str__(self):
        return self.address


class About(models.Model):
    '''О магазине'''
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(verbose_name='О нас')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'О нас'
        verbose_name_plural = 'О магазине'
        ordering = ['-created']

    def __str__(self):
        return self.title


class PrivacyPolicy(models.Model):
    '''Политика конфиденциальности'''
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Политика'
        verbose_name_plural = 'Политика'
        ordering = ['-created']

    def __str__(self):
        return self.title


class Delivery(models.Model):
    '''Информация о доставке товаров'''
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Доставка'
        verbose_name_plural = 'Доставка'
        ordering = ['-created']

    def __str__(self):
        return self.title


class Backcall(models.Model):
    '''Форма обратного звонка'''
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    phone = models.CharField(max_length=100, verbose_name='Телефон')
    text = models.TextField(max_length=1000, blank=True, verbose_name='Сообщение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    class Meta:
        verbose_name = 'Обратный звонок'
        verbose_name_plural = 'Обратный звонок'
        ordering = ['-created']

    def __str__(self):
        return self.full_name


class HeaderWidgetInfo(models.Model):
    '''Виджеты (working time, Free shipping, Money back 100%, Phone:) '''
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    text = models.CharField(max_length=50, verbose_name='Текст')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')

    class Meta:
        verbose_name = 'Виджет'
        verbose_name_plural = 'Виджеты'

    def __str__(self):
        return '{} - {}'.format(self.title, self.text)

contacts/forms.py
from django import forms
from captcha.fields import CaptchaField
from contacts.models import Contacts, Backcall


class ContactForm(forms.ModelForm):
    '''Форма обратной связи с капчей'''
    captcha = CaptchaField(label='Введите проверочный код ', )

    class Meta:
        model = Contacts
        fields = ['full_name', 'phone', 'email', 'text']

        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'Your Name', 'class': 'form-control', 'required': True}),
            'phone': forms.TextInput(attrs={'placeholder': 'Your Phone', 'class': 'form-control', 'required': True}),
            'email': forms.EmailInput(attrs={'placeholder': 'Please enter your email', 'class': 'form-control', 'required': True}),
            'text': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Please enter your enquiry', 'class': 'form-control', 'required': True}),

        }


class BackcallForm(forms.ModelForm):
    '''Форма обратного звонка с капчей'''
    captcha = CaptchaField(label='Введите проверочный код ', )

    class Meta:
        model = Backcall
        fields = ['full_name', 'phone', 'text']

        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': 'Your Name', 'class': 'form-control', 'required': True}),
            'phone': forms.TextInput(attrs={'placeholder': 'Your Phone', 'class': 'form-control', 'required': True}),
            'text': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Please enter your enquiry', 'class': 'form-control', 'required': False}),

        }

contacts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect
from contacts.models import Contacts, Maps, About, Address, Delivery, HeaderWidgetInfo
from contacts.forms import ContactForm, BackcallForm

# Подгружаем настройки из модуля local_settings.py.
from myshop3.local_settings import DEFAULT_FROM_EMAIL, DOUBLE_ADMIN_EMAIL


def contact(request):
    '''Обработка формы обратной связи и вывод карты расположения объекта.'''
    context = {}
    map_url = Maps.objects.filter(is_active=True)
    address = Address.objects.filter(is_active=True)

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            text = form.cleaned_data['text']
            recepients = [DEFAULT_FROM_EMAIL] # емейл админа, на него придет сообщение от пользователя
            admin_recepients = [DOUBLE_ADMIN_EMAIL] # второй емейл админа (дубль), на него придет сообщение от пользователя
            contact = form.save(commit=False)
            contact.save()

            context = {
                'full_name': full_name,
                'phone': phone,
                'email': email,
                'text': text,
                'contact': contact,
            }

            message = render_to_string('admin_contact_email.html', context, request)
            email = EmailMessage('Поступило новое сообщение с сайта №{} от "{}" ' .format(contact.id, full_name), message, DEFAULT_FROM_EMAIL, recepients, admin_recepients)
            email.content_subtype = 'html'
            email.send()
            messages.success(request, 'Ваше сообщение успешно отправлено!')
            return HttpResponseRedirect('/contact/')
        else:
            messages.error(request, 'Произошла ошибка, попробуйте отправить еще раз.')
    else:
        form = ContactForm()

    context['map_url'] = map_url
    context['address'] = address
    context['form'] = form

    return render(request, 'contact.html', context)


def about(request):
    '''О магазине'''
    about = About.objects.filter(is_active=True)
    context = {
        'about': about,
    }
    return render(request, 'about.html', context)


def backcall(request):
    '''Обратный звонок'''
    if request.method == 'POST':
        form = BackcallForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            full_name = form.cleaned_data['full_name']
            phone = form.cleaned_data['phone']
            text = form.cleaned_data['text']
            recepients = [DEFAULT_FROM_EMAIL] # емейл админа, на него придет сообщение от пользователя
            admin_recepients = [DOUBLE_ADMIN_EMAIL]  # второй емейл админа (дубль), на него придет сообщение от пользователя
            backcall = form.save(commit=False)
            backcall.save()

            context = {
                'full_name': full_name,
                'phone': phone,
                'text': text,
                'backcall': backcall,
            }

            message = render_to_string('admin_backall_email.html', context, request)
            email = EmailMessage('Поступил заказ обратного звонка №{} от "{}" '.format(backcall.id, full_name), message, DEFAULT_FROM_EMAIL, recepients, admin_recepients)
            email.content_subtype = 'html'
            email.send()
            messages.success(request, 'Ваше сообщение успешно отправлено!')
        else:
            messages.error(request, 'Произошла ошибка, попробуйте отправить еще раз.')
    else:
        form = BackcallForm()

    return render(request, 'modal_backcall.html', {'form': form})


def delivery(request):
    '''Доставка'''
    delivery = Delivery.objects.filter(is_active=True)
    return render(request, 'delivery.html', {'delivery': delivery})

contacts/templates/about.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block title %}{{ about.last }}{% endblock %}

{% block content %}
<!-- START PAGE-CONTENT -->
<section class="page-content">
    <div class="container">
        <div class="row">
                <div class="col-md-12">
                    <ul class="page-menu">
                        <li><a href="/">Главная</a></li>
                        <li class="active"><a href="{% url 'contacts:about' %}">О нас</a></li>
                    </ul>
                </div>
            {% for abt in about %}
            <div class="text-center">
                <h1>{{ abt.title }}</h1>
                <div style="font-size: 16px; text-align: justify">

                    {{ abt.text|safe }}

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- End Our-Team -->
</section>


{% endblock content %}

contacts/templates/contact.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block title %}{{ address.title }}{% endblock %}

{% block content %}

<style>

:focus::-webkit-input-placeholder {color: transparent}
:focus::-moz-placeholder          {color: transparent}
:focus:-moz-placeholder           {color: transparent}
:focus:-ms-input-placeholder      {color: transparent}


/* Conatct start  для блока MAIL & WEBSITE, CONTACT, ADDRESS */

.box > .icon { text-align: center; position: relative; }
.box > .icon > .image { position: relative; z-index: 2; margin: auto; width: 88px; height: 88px; border: 8px solid white; line-height: 88px; border-radius: 50%; background: #00bfff; vertical-align: middle; }
.box > .icon:hover > .image { background: #333; }
.box > .icon > .image > i { font-size: 36px !important; color: #fff !important; }
.box > .icon:hover > .image > i { color: white !important; }
.box > .icon > .info { margin-top: -24px; background: rgba(0, 0, 0, 0.04); border: 1px solid #e0e0e0; padding: 15px 0 10px 0; min-height:185px;}
.box > .icon:hover > .info { background: rgba(0, 0, 0, 0.04); border-color: #e0e0e0; color: white; }
.box > .icon > .info > h3.title { font-family: "Robot",sans-serif !important; font-size: 16px; color: #222; font-weight: 700; }
.box > .icon > .info > p { font-family: "Robot",sans-serif !important; font-size: 15px; color: #666; line-height: 1.5em; margin: 20px; margin-left: 10px;}
.box > .icon:hover > .info > h3.title, .box > .icon:hover > .info > p, .box > .icon:hover > .info > .more > a { color: #222; }
.box > .icon > .info > .more a { font-family: "Robot",sans-serif !important; font-size: 12px; color: #222; line-height: 12px; text-transform: uppercase; text-decoration: none; }
.box > .icon:hover > .info > .more > a { color: #fff; padding: 6px 8px; background-color: #63B76C; }
.box .space { height: 30px; }

@media only screen and (max-width: 768px)
{
    .contact-form
    {
        margin-top:25px;
    }

    .btn-send
    {
        width: 100%;
        padding:10px;
    }

    .second-portion
    {
        margin-top:25px;
    }
}
/* Conatct end */

</style>

		<!-- START PAGE-CONTENT -->
		<section class="page-content">
			<div class="container">
	            <div class="row">
					<div class="col-md-12">
						<ul class="page-menu">
							<li><a href="/">Главная</a></li>
							<li class="active"><a href="{% url 'contacts:contact' %}">Контакты</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						{% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
						{% include 'shop/bestseller.html' %} <!--Подгружаем код из файла shop/bestseller.html -->
					</div>
					<div class="col-md-9">
						<!-- Start Map area -->
                        {% for map in map_url %}
                            <div class="map-area">
                                <iframe src="{{ map.maps }}" width="100%" height="350px" frameborder="1" allowfullscreen="true"></iframe>

    {#							<div id="googleMap" style="width:100%;height:350px;"></div>#}
                            </div>
                        {% endfor %}
                        <br>
						<!-- End Map area -->

                            <!-- Блок MAIL & WEBSITE, CONTACT, ADDRESS -->
                    {% for adres in address %}
                            <div class="row">
                                <!-- Boxes de Acoes -->
                                <div class="col-xs-12 col-sm-6 col-lg-4">
                                    <div class="box">
                                        <div class="icon">
                                            <div class="image"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                                            <div class="info">
                                                <h3 class="title">MAIL & WEBSITE</h3>
                                                <p>
                                                    <i class="fa fa-envelope" aria-hidden="true"></i> &nbsp
                                                    {{ adres.email_one }}
                                                    <br>
                                                    <br>
                                                    <i class="fa fa-globe" aria-hidden="true" style="margin-right: 5px;"></i> &nbsp
                                                    {{ adres.website }}
                                                </p>

                                            </div>
                                        </div>
                                        <div class="space"></div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-6 col-lg-4">
                                    <div class="box">
                                        <div class="icon">
                                            <div class="image"><i class="fa fa-mobile" aria-hidden="true"></i></div>
                                            <div class="info">
                                                <h3 class="title">PHONE</h3>
                                                <p>
                                                    <i class="fa fa-mobile" aria-hidden="true"></i> &nbsp
                                                    {{ adres.phone_one }}
                                                    <br>
                                                    <br>
                                                    <i class="fa fa-mobile" aria-hidden="true"></i> &nbsp
                                                    {{ adres.phone_two }}
                                                </p>
                                            </div>
                                        </div>
                                        <div class="space"></div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-6 col-lg-4">
                                    <div class="box">
                                        <div class="icon">
                                            <div class="image"><i class="fa fa-map-marker" aria-hidden="true"></i></div>
                                            <div class="info">
                                                <h3 class="title">ADDRESS</h3>
                                                <p>
                                                    <i class="fa fa-map-marker" aria-hidden="true"></i> &nbsp
                                                     {{ adres.address }}
                                                    <br>
                                                    <br>
                                                    <i class="fa fa-clock-o" aria-hidden="true"></i> &nbsp Пон- Суб: 9.00 - 17.00
                                                </p>
                                            </div>
                                        </div>
                                        <div class="space"></div>
                                    </div>
                                </div>
                                <!-- /Boxes de Acoes -->
                            </div>
                    {% endfor %}
                            <!-- / Блок MAIL & WEBSITE, CONTACT, ADDRESS -->


                        {% if messages %}
                            {% for message in messages %}
                              <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                              </div>
                            {% endfor %}
                        {% endif %}

						<!-- Start Contact-Message -->
						<div class="contact-message">
							<fieldset>
								<form method="post" action="{% url 'contacts:contact' %}">
                                    {% csrf_token %}
									<legend>Форма обратной связи</legend>
									<div class="form-group form-horizontal">
										<div class="row">
											<label class="col-sm-2 control-label"><sup>*</sup>ФИО</label>
											<div class="col-sm-10">
												{{ form.full_name }}
											</div>
										</div>
									</div>
									<div class="form-group form-horizontal">
										<div class="row">
											<label class="col-sm-2 control-label"><sup>*</sup>Телефон</label>
											<div class="col-sm-10">
												{{ form.phone }}
											</div>
										</div>
									</div>
									<div class="form-group form-horizontal">
										<div class="row">
											<label class="col-sm-2 control-label"><sup>*</sup>E-Mail</label>
											<div class="col-sm-10">
												{{ form.email }}
											</div>
										</div>
									</div>
									<div class="form-group form-horizontal">
										<div class="row">
											<label class="col-sm-2 control-label"><sup>*</sup>Сообщение</label>
											<div class="col-sm-10">
												{{ form.text }}
											</div>
										</div>
									</div>
                                    <div class="row">
                                        <label class="col-sm-12 control-label"><sup>*</sup>Поля, отмеченные звездочкой, являются обязательными!</label>
                                    </div>
                                    <div class="col-md-12">
                                      <div class="form-group pull-right">
                                        <label for="id_captcha">Captcha: {{ form.captcha.label }}<sup>*</sup>
                                            <span style="color: red; display: inherit;">{{ form.captcha.errors }}</span>
                                        </label>
                                          <div class="container-fluid">
                                            <div class="row">
                                                {{ form.captcha }}
                                                <button class='captcha-refresh'>
                                                    <img src="{% static 'info/news/icon/reload.png' %}" alt="reload">
                                                </button>
                                            </div>
                                           </div>
                                        <div class="help-block with-errors"></div>
                                      </div>
                                    </div>
                                    <div class="pull-right">
                                        <input id="checkbox" type="checkbox" name="checkbox" onchange="document.getElementById('submit').disabled = !this.checked;" />
                                            <label for="form">
                                                Я прочитал и согласен с нашей
                                            </label>
                                        <a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">политикой</a><!-- Модальное окно в шаблоне modal_privacy_policy.html -->
                                        <input class="btn btn-primary" type="submit" disabled="disabled" name="submit" id="submit" value="Отправить" style="margin-left: 5px;">
                                    </div>
								</form>
							</fieldset>
						</div>
						<!-- End Contact-Message -->
					</div>
				</div>
			</div>

        </section>
{% endblock content %}

contacts/templates/delivery.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block title %}{{ delivery.last }}{% endblock %}

{% block content %}


    <!-- START PAGE-CONTENT -->
    <section class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="page-menu">
                        <li><a href="/">Главная</a></li>
                        <li class="active"><a href="{% url 'contacts:delivery' %}">Информация о доставке</a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    {% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
                    {% include 'shop/bestseller.html' %} <!--Подгружаем код из файла shop/bestseller.html -->
                </div>
                <div class="col-md-9">
                    {% if delivery %}

                        {% for del in delivery %}
                            <h1 class="text-center">{{ del.title }}</h1>
                            <p>{{ del.text|safe }}</p>
                        {% endfor %}
                        {% else %}
                        <p class="text-center">Страница временно не доступна.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>


{% endblock %}

contacts/templates/header_info.html
{% load staticfiles %}

        {% if widgets %}
            <div class="support-client hidden-xs">
                <div class="row">
                    <!-- Start Single-Support -->
                    {% for widget in widgets %}
                    <div class="col-md-3 hidden-sm">
                        <div class="single-support">
                            <div class="support-content">
                                <i class="fa fa-clock-o"></i>
                                <div class="support-text">
                                    <h1 class="zero gfont-1" style="font-family: 'Roboto', sans-serif;">{{ widget.title }}</h1>
                                    <p>{{ widget.text }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- End Single-Support -->
                </div>
            </div>
            {% else %}

        {% endif %}

contacts/templates/modal_privacy_policy.html
<!-- Modal выводится в шаблоне base.html-->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel" style="text-align: center">{{ privacy_policy.title }}</h4>
      </div>
      <div class="modal-body">
        {{ privacy_policy.text|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>