cart/urls.py
from django.urls import path
from cart.views import (CartTemplateView, CartInfoTemplateView, CartAddFormView,
                        CartChangeFormView, CartRemoveFormView, CheckoutTemplateView)


app_name = 'cart'

urlpatterns = [
    path('', CartTemplateView.as_view(), name='cart'),
    path('info/', CartInfoTemplateView.as_view(), name='info'),
    path('add/', CartAddFormView.as_view(), name='add'),
    path('change/', CartChangeFormView.as_view(), name='change'),
    path('remove/', CartRemoveFormView.as_view(), name='remove'),
    path('checkout/', CheckoutTemplateView.as_view(), name='checkout'),
]

cml/urls.py
from __future__ import absolute_import
from django.conf.urls import re_path, include
from . import views

app_urlpatterns = [
    re_path(r'^1c_exchange.php$', views.front_view, name='front_view'),
    re_path(r'^exchange$', views.front_view, name='front_view'),
]

urlpatterns = [
    re_path(r'^', include((app_urlpatterns, 'cml'), namespace='cml')),
]

myshop3/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include, re_path
import debug_toolbar
import notifications.urls


def robots(request):
    return render(request, 'shop/robots.txt', content_type='text/plain')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('summernote/', include('django_summernote.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('news/', include('info.urls', namespace='news')),
    path('reviews/', include('info.urls', namespace='reviews')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/profile/', include('profiles.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('profiles.accounts_urls')),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('chaining/', include('smart_selects.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)), # Использует debug_toolbar

    re_path(r'^cml/', include('cml.urls')),

    path('robots.txt', robots, name='robots'),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.views.generic import TemplateView

from orders.views import order_create, thanks

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='create_orders'),
    #path('create/thanks/', TemplateView.as_view(template_name='orders/thanks.html'), name='thanks'),
    path('create/thanks/', thanks, name='thanks'),


]

shop/urls.py
from django.urls import path
from .views import (index, catalog, catlist, catlinks,
                    shoplist, productdetails,
                    modalproduct, compareproducts,
                    products_by_brand, search,
                    notify_create,
                    price_list_count,



                    )


app_name = 'shop'

urlpatterns = [
    path('', index, name='index_page'),
    path('category/<int:pk>/sort/brand/', products_by_brand, name='products-all'),
    path('category/<int:pk>/sort/brand/<slug>/', products_by_brand, name='products-by-brand'),
    path('catalog/', catalog, name='catalog'),
    path('catalog/catlist/<slug>/', catlist, name='catlist'),
    path('catlinks/<slug>/', catlinks, name='catlinks'),
    #path('shop/', shop, name='shop'),
    path('shop-list/<slug>/', shoplist, name='shop-list'),
    path('product-details/<str:product_slug>/', productdetails, name='product-details'),
    path('modal-product/<slug>/', modalproduct, name='modal-product'),
    path('compare-products/<category_slug>/', compareproducts, name='compare-products-by-category'),
    path('compare-products/', compareproducts, name='compare-products'),
    path('search/', search, name='search'),
    path('notify_create/', notify_create, name='notify_create'),
    path('price/<pk>/', price_list_count, name='price_list_count'),




]

orders/models.py
from django.conf import settings
from django.db import models

from cart.models import Cart, CartProduct
from shop.models import Product

from model_utils import Choices  #https://django-model-utils.readthedocs.io/en/latest/utilities.html


STATUS = Choices(
    (0, 'registration', 'На регистрации'),
    (1, 'execution', 'На исполнении'),
    (2, 'executed', 'Исполнен')
)

BUYING_TYPE = Choices(
    ('take_out', 'Самовывоз'),
    ('delivery', 'Доставка'),
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Пользователь')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='Корзина')
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00, verbose_name='Всего')
    full_name = models.CharField(max_length=250, default='', verbose_name='Фио')
    phone = models.CharField(max_length=25, verbose_name='Телефон')
    email = models.EmailField(max_length=100, verbose_name='email', blank=True)
    address = models.CharField(max_length=250, verbose_name='Адрес', blank=True)
    buying_type = models.CharField(max_length=100, verbose_name='Тип заказа', choices=BUYING_TYPE, default='take_out')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    delivery_date = models.DateField(blank=True, null=True, verbose_name='Дата доставки')
    comment = models.TextField(verbose_name='Комментарий к заказу')
    status = models.IntegerField(choices=STATUS, default=STATUS.registration, verbose_name='Статус заказа')


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return '№{0}'.format(str(self.id))

orders/forms.py
from django import forms
from django.utils import timezone
from model_utils import Choices

BUYING_TYPE = Choices(
    ('take_out', 'Самовывоз'),
    ('delivery', 'Доставка'),
)


class OrderForm(forms.Form):
    '''Форма создания заказа для анонимного пользователя'''
    full_name = forms.CharField(required=True)
    phone = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=BUYING_TYPE)
    address = forms.CharField(required=False)
    delivery_date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    comment = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].label = '* ФИО'
        self.fields['phone'].label = '* Контактный телефон'
        self.fields['phone'].help_text = 'Пожалуйста, указывайте реальный номер телефона, по которому с Вами можно связаться'
        self.fields['email'].label = '* Ваш e-mail на него придет копия заказа'
        self.fields['email'].help_text = 'Ваш e-mail адрес'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Укажите адрес доставки'
        self.fields['address'].help_text = '*Обязательно указывайте город, почтовый индекс, улица, дом, квартира!'
        self.fields['comment'].label = 'Комментарий к заказу'
        self.fields['delivery_date'].label = 'Дата доставки'
        self.fields['delivery_date'].help_text = 'Доставка производится на следущий день после оформления заказа. Менеджер с Вами предварительно свяжется!'

orders/views.py
#from django.contrib.auth.decorators import login_required
from urllib.parse import urlparse

from django.shortcuts import render, HttpResponseRedirect
from django.urls import resolve, reverse

from myshop3.local_settings import DEFAULT_FROM_EMAIL, DOUBLE_ADMIN_EMAIL
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from orders.forms import OrderForm
from orders.models import Order
from django.http import Http404


def order_create(request):
    '''Создание заказа'''
    '''До else отрабатывает для не авторизованного пользователя, после else для авторизованного'''
    cart = request.cart
    if request.method == 'POST':
        form = OrderForm(request.POST or None)
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            buying_type = form.cleaned_data['buying_type']
            delivery_date = form.cleaned_data['delivery_date']
            address = form.cleaned_data['address']
            comment = form.cleaned_data['comment']
            recepients = [DEFAULT_FROM_EMAIL] # емейл админа, на него придет заказ от пользователя
            admin_recepients = [DOUBLE_ADMIN_EMAIL] # второй емейл админа (дубль), на него придет заказ от пользователя
            user_recepients = [email] # емейл пользователя, на него придет его заказ
            cart = request.cart
            order = Order.objects.create(
                #user=request.user,
                cart=request.cart,
                total=cart.discount_price,
                full_name=full_name,
                phone=phone,
                email=email,
                address=address,
                buying_type=buying_type,
                delivery_date=delivery_date,
                comment=comment,
                user=request.user if request.user.is_authenticated else None #Если пользователь не авторизован, то может сделать заказ.

            )

            context = {
                'full_name': full_name,
                'phone': phone,
                'email': email,
                'buying_type': buying_type,
                'delivery_date': delivery_date,
                'address': address,
                'comment': comment,
                'cart': cart,
                'order': order,
                #'id': order.id,
                #'date': order.date,
            }

            '''Отправляем письмо админу'''
            message = render_to_string('orders/admin_email.html', context, request)
            #email = EmailMessage('Поступил новый заказ: №' + str(order.id) + ' ' + full_name, message, 'blazer-05@mail.ru', recepients)
            if request.user.is_authenticated:
                email = EmailMessage('Поступил новый заказ. {} от пользователя "{}" '.format(order, request.user),
                                     message, DEFAULT_FROM_EMAIL, recepients, admin_recepients) #'blazer-05@mail.ru' - это адрес отправителя!
            else:
                email = EmailMessage('Поступил новый заказ. {} от анонимного пользователя "{}" '.format(order, full_name),
                                     message, DEFAULT_FROM_EMAIL, recepients, admin_recepients) #'blazer-05@mail.ru' - это адрес отправителя!
            email.content_subtype = 'html'
            email.send()

            '''Отправляем письмо пользователю'''
            user_message = render_to_string('orders/user_order_email.html', context, request)
            if request.user.is_authenticated:
                user_email = EmailMessage('Спасибо за Ваш заказ. {}'.format(order), user_message, DEFAULT_FROM_EMAIL,
                                          to=[request.user.email])
            else:
                user_email = EmailMessage('Спасибо за Ваш заказ. {}'.format(order), user_message, DEFAULT_FROM_EMAIL,
                                          user_recepients)
            user_email.content_subtype = 'html'
            user_email.send()

            request.cart.clear()

            return HttpResponseRedirect('thanks')
    else:
        '''Если пользователь авторизован, то инициализируем-заполняем форму значениями из профиля пользователя,
        чтобы в админке в заказе было указано от какого авторизованного пользователя поступил заказ.'''
        initial = {}
        user = request.user
        if user.is_authenticated:
            profile = user.profile
            initial['full_name'] = '{} {}'.format(profile.last_name, profile.first_name)
            initial['phone'] = profile.phone
            initial['email'] = user.email

        form = OrderForm(initial=initial)

    return render(request, 'orders/orders.html', {'form': form, 'cart': cart})


def thanks(request):
    '''Страница thanks'''
    '''Проверяем урл с которого пришел пользователь должен быть равен урлу создания заказа. Тогда страница thanks 
    не будет доступна всем, только тем кто сделал заказ.'''
    referer = request.META.get('HTTP_REFERER')
    if urlparse(referer).path == reverse('order:create_orders'):
        return render(request, 'orders/thanks.html')
    raise Http404()

orders/templates/orders/orders.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load bootstrap3 %}
{% load banner %}

{% block title %}
    Оформление заказа - интернет магазин Tehnostyle
{#    {% for p in cart.products.all %}#}
{#        {{ p.title }},#}
{#    {% endfor %}#}
{% endblock %}

{% block content %}
		<!-- START PAGE-CONTENT -->
		<section class="page-content">
			<div class="container">
	            <div class="row">
					<div class="col-md-12">
						<ul class="page-menu">
							<li><a href="/">Главная</a></li>
                            <li><a href="{% url 'cart:checkout' %}">Проверить</a></li>
							<li class="active"><a href="{% url 'order:create_orders' %}">Оформление заказа</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						{% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
					</div>
					<div class="col-md-9">
						<!-- START PRODUCT-BANNER -->
						<div class="product-banner">
							<div class="row">
                                {% center_big_banner %} <!-- Большой баннер 870×216 -->
							</div>
                            <div class="cart-title">
                                <h2>Оформление заказа</h2><!-- Для английского шрифта указаьть class="entry-title"  -->
                            </div>
						</div>
						<!-- END PRODUCT-BANNER -->
                    {% if request.cart.cartproduct_set.all %}
						<div class="Wishlist-area">
                            <div class="panel-group" id="accordion">
                                <div class="panel panel_default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a class="accordion-trigger" data-toggle="collapse" data-parent="#accordion" href="#checkout-confirm" style="font-weight: inherit;">
                                                Оформление заказа <i class="fa fa-caret-down"></i>
                                            </a>
                                        </h4>
                                    </div>
                                    <div id="checkout-confirm" class="collapse in">
                                        <div class="panel-body">

                                            <div class="table-responsive">
                                                <table class="table table-bordered table-hover bmw">
                                                    <thead>
                                                        <tr>
                                                            <td class="text-center">Изображение</td>
                                                            <td class="text-left">Наименование</td>
                                                            <td class="text-center">Количество</td>
                                                            <td class="text-right">Цена</td>
                                                            <td class="text-right">Всего</td>
                                                        </tr>
                                                    </thead>
                                                    {% for item in request.cart.cartproduct_set.all %}
                                                    <tbody>
                                                        <tr>
                                                            <td class="text-center">
                                                                {% if item.product.images %}
                                                                <img class="img-thumbnail" src="{{ item.product.images|thumbnail_url:'cart' }}" alt="{{ item.product.title }}" />
                                                                {% else %}
                                                                    <img class="img-thumbnail"
                                                                         src="{% static 'shop/img/no-image-70x70.png' %}"/>
                                                                {% endif %}
                                                            </td>
                                                            <td class="text-left">{{ item.product.title }}<br><br><small>Артикул: <span class="text-stock">{{ item.product.vendor_code }}</span></small></td>
                                                            <td class="text-center">{{ item.quantity }}</td>
                                                            <td class="text-right">&#8381; {{ item.product.price }}</td>
                                                            <td class="text-right">&#8381; {{ item.discount_price }}</td>
                                                        </tr>
                                                    </tbody>
                                                    {% endfor %}
                                                    <tfoot>
                                                        <tr>
                                                            <td class="text-right" colspan="4">
                                                                <strong>Всего:</strong>
                                                            </td>
                                                            <td class="text-right">&#8381; {{ request.cart.discount_price }}</td>
                                                        </tr>
                                                        <tr>
                                                            <td class="text-right" colspan="4">
                                                                <strong>Количество:</strong>
                                                            </td>
                                                            <td class="text-right">{{ request.cart.count_products }} шт.</td>
                                                        </tr>
                                                    </tfoot>
                                                </table>
                                            </div>
                                            {% if not request.user.is_authenticated %}
                                            <h2>Заполните форму</h2>
                                                {% else %}
                                                <h2>Проверьте ваши данные</h2>
                                            {% endif %}
                                                <form action="{% url 'order:create_orders' %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="col-sm-13">
{#                                                    {% bootstrap_form form layout='inline' %}#}
                                                        <sup>*</sup> {% bootstrap_label 'ФИО' %}
                                                        {% bootstrap_field form.full_name show_label=False %}
                                                        <sup>*</sup> {% bootstrap_label 'Телефон' %}
                                                        {% bootstrap_field form.phone show_label=False %}
                                                        <sup>*</sup> {% bootstrap_label 'E-mail' %}
                                                        {% bootstrap_field form.email show_label=False %}
                                                        {% bootstrap_field form.buying_type show_label=False %}
                                                        {% bootstrap_field form.address show_label=False %}
                                                        {% bootstrap_field form.delivery_date show_label=False %}
                                                        {% bootstrap_field form.comment show_label=False %}

                                                        {% if not request.user.is_authenticated %}
                                                            <p class="pull-left">
                                                            <span>
                                                                Поля отмеченные <sup>*</sup> обязательны к заполнению!
                                                            </span>
                                                            </p>
                                                        {% endif %}
                                                    <input type="submit" class="btn btn-primary pull-right" value="Отправить">
                                                    </div>
                                                </form>

                                            <script src="{% static 'shop/js/jquery-1.11.3.min.js' %}"></script>
                                            <!-- Скрипт скрывающие поле "адрес" в форме -->
                                            <script>
                                                $(document).ready(function(){
                                                    $('#id_address').css('display', 'none');
                                                    $('.help-block').css('display', 'none');
                                                    $('#id_delivery_date_day').css('display', 'none');
                                                    $('#id_delivery_date_month').css('display', 'none');
                                                    $('#id_delivery_date_year').css('display', 'none');
                                                    $('#id_buying_type').on('click', function(){
                                                        buying_type = $(this).val();
                                                        if(buying_type == 'delivery'){
                                                            $('#id_address').css('display', 'block');
                                                            $('.help-block').css('display', 'block');
                                                            $('#id_delivery_date_day').css('display', 'block');
                                                            $('#id_delivery_date_month').css('display', 'block');
                                                            $('#id_delivery_date_year').css('display', 'block');
                                                        }else{
                                                            $('#id_address').css('display', 'none');
                                                            $('.help-block').css('display', 'none');
                                                            $('#id_delivery_date_day').css('display', 'none');
                                                            $('#id_delivery_date_month').css('display', 'none');
                                                            $('#id_delivery_date_year').css('display', 'none');
                                                        }
                                                    })
                                                })
                                            </script>
                                        </div>
                                    </div>
                                </div>
                            </div>
						</div>
                        {% else %}
                           <div class="shopping-checkout">
                                <h2>Ваша корзина пуста</h2><!-- Для английского шрифта указаьть class="entry-title" -->
                                <a href="{% url 'shop:catalog' %}" class="btn btn-success pull-left">Продолжить покупки</a>
                            </div>
                    {% endif %}
					</div>
				</div>
			</div>
        </section>
{% endblock content %}

orders/templates/orders/thanks.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% load bootstrap3 %}
{% load banner %}

{% block title %}
    Thanks
{% endblock %}

{% block content %}
		<!-- START PAGE-CONTENT -->
		<section class="page-content">
			<div class="container">
	            <div class="row">
					<div class="col-md-12">
						<ul class="page-menu">
							<li><a href="/">Главная</a></li>
							<li class="active"><a href="{% url 'order:thanks' %}">Спасибо за ваш заказ!</a></li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						{% include 'shop/menu-category.html' %} <!-- Подгружаем код из шаблона shop/menu-category.html -->
					</div>
					<div class="col-md-9">
						<!-- START PRODUCT-BANNER -->
						<div class="product-banner">
							<div class="row">
                                {% center_big_banner %} <!-- Большой баннер 870×216 -->
							</div>
						</div>
						<!-- END PRODUCT-BANNER -->
                        <h1>Ваш заказ принят!</h1>
                        <h3>Автоматический переход на главную страницу через <span id="id_seconds" style="color: red;"></span> секунд.</h3>
{#						<div class="Wishlist-area">#}
{#                            <div class="panel-group" id="accordion">#}
{#                                <div class="panel panel_default">#}
{#                                    <div class="panel-heading">#}
{#                                        <h4 class="panel-title">#}
{#                                            <a class="accordion-trigger" data-toggle="collapse" data-parent="#accordion" href="#checkout-confirm">Create Order <i class="fa fa-caret-down"></i> </a>#}
{#                                        </h4>#}
{#                                    </div>#}
{##}
{#                                </div>#}
{#                            </div>#}
{#						</div>#}
					</div>
				</div>
			</div>
        </section>

        <script type="text/javascript">

            /*Изменить текущий адрес страницы через 3 секунды (3000 миллисекунд)*/
            change_seconds = (seconds) => {
              document.getElementById('id_seconds').innerText = seconds;
            };

            redirect_timer = () => {
                let seconds = 10;
                change_seconds(seconds);
                let interval = setInterval(
                    () => {
                        seconds--;
                        change_seconds(seconds);
                        if (seconds <= 0) {
                            clearInterval(interval);
                            location.replace("/")
                        }
                    }, 1000);
            };

            redirect_timer();

        </script>

{% endblock content %}