cml/urls.py
from __future__ import absolute_import
from django.conf.urls import re_path, include
from . import views

app_urlpatterns = [
    re_path(r'^1c_exchange.php$', views.front_view, name='front_view'),
    re_path(r'^exchange$', views.front_view, name='front_view'),
]

urlpatterns = [
    re_path(r'^', include((app_urlpatterns, 'cml'), namespace='cml')),
]

myshop3/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include, re_path
import debug_toolbar
import notifications.urls


def robots(request):
    return render(request, 'shop/robots.txt', content_type='text/plain')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('summernote/', include('django_summernote.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='order')),
    path('news/', include('info.urls', namespace='news')),
    path('reviews/', include('info.urls', namespace='reviews')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/profile/', include('profiles.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('profiles.accounts_urls')),
    path('accounts/', include('allauth.urls')),
    path('contact/', include('contacts.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('chaining/', include('smart_selects.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)), # Использует debug_toolbar

    re_path(r'^cml/', include('cml.urls')),

    path('robots.txt', robots, name='robots'),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from .views import (
    newsletter_unsubscribe,
    subscribe, control_newsletter,
    control_newsletter_list,
    control_newsletter_detail,
    control_newsletter_edit,
    control_newsletter_delete,
    control_newsletter_search,
    control_newsletter_templates,

    )

app_name = 'newsletter'

urlpatterns = [
    path('subscribe/', subscribe, name='subscribe'),
    path('unsubscribe/', newsletter_unsubscribe, name='newsletter_unsubscribe'),
    path('dashboard/', control_newsletter, name='control_newsletter'),
    path('dashboard/list/', control_newsletter_list, name='control_newsletter_list'),
    path('dashboard/detail/<int:pk>/', control_newsletter_detail, name='control_newsletter_detail'),
    path('dashboard/edit/<int:pk>/', control_newsletter_edit, name='control_newsletter_edit'),
    path('dashboard/delete/<int:pk>/', control_newsletter_delete, name='control_newsletter_delete'),
    path('dashboard/search/', control_newsletter_search, name='control_newsletter_search'),
    path('dashboard/templates/', control_newsletter_templates, name='control_newsletter_templates'),

]

newsletter/models.py
from django.db import models
from model_utils import Choices
from shop.models import Product


class NewsletterUser(models.Model):
    '''Модель email подписки'''
    name = models.CharField(max_length=250, blank=True, verbose_name='ФИО')
    email = models.EmailField(verbose_name='email')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return self.email


class Newsletter(models.Model):
    '''Рассылка сообщений'''
    EMAIL_STATUS_CHOICES = Choices(
        (1, 'Draft', 'Черновик'),
        (2, 'Published', 'Опубликовано')
    )

    subject = models.CharField(max_length=250, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое')
    users_email = models.ManyToManyField(NewsletterUser, verbose_name='email')
    status = models.IntegerField(choices=EMAIL_STATUS_CHOICES, verbose_name='Статус')
    file = models.FileField(upload_to='newsletter_files/%Y/%m/%d', blank=True, verbose_name='Файл')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return self.subject


class Template(models.Model):
    '''email шаблоны'''
    name = models.CharField(max_length=250, verbose_name='Название')
    text = models.TextField(blank=True, verbose_name='Шаблон')
    products = models.ManyToManyField(Product, related_name='prod_tpl', blank=True, verbose_name='Товары')
    is_active = models.BooleanField(default=True, verbose_name='Модерация')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        verbose_name = 'Шаблон'
        verbose_name_plural = 'Шаблоны'

    def __str__(self):
        return self.name

newsletter/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import NewsletterUser, Newsletter


class NewsletterUserSignUpForm(forms.ModelForm):
    '''Форма email подписки'''

    class Meta:
        model = NewsletterUser
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        return email


class NewsletterCreationForm(forms.ModelForm):
    '''Форма отправки рассылки'''

    class Meta:
        model = Newsletter
        fields = ['subject', 'body', 'users_email', 'file', 'status']

        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': 'Headline', 'class': 'form-control', 'required': True}),
            'status': forms.Select(attrs={'class': 'form-control', 'required': True}),
            'file': forms.FileInput(),
            #'users_email': forms.SelectMultiple(attrs={'size': 10, 'class': 'special'}),
            'users_email': forms.CheckboxSelectMultiple(),
            'body': SummernoteWidget(attrs={
                'summernote': {
                    'airMode': False,
                    'width': '100%',
                    'height': '800',
                    # 'toolbar': [
                    #     ['style', ['bold', 'italic', 'underline', 'clear']],
                    #     ['font', ['strikethrough', 'superscript', 'subscript']],
                    #     ['fontsize', ['fontsize']],
                    #     ['color', ['color']],
                    #     ['para', ['ul', 'ol', 'paragraph']],
                    #     ['height', ['height']],
                    #     ['misc', ['codeview']],
                    # ],

                },

            }),

        }

newsletter/views.py
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q
from smtplib import SMTPDataError

from myshop3.settings import site_url
from myshop3 import local_settings
from .models import NewsletterUser, Newsletter, Template
from .forms import NewsletterUserSignUpForm, NewsletterCreationForm


def subscribe(request):
    '''Подписка на рассылку'''
    if not request.is_ajax() or request.method != 'POST':
        return HttpResponseForbidden()

    form = NewsletterUserSignUpForm(request.POST)
    if not form.is_valid():
        return JsonResponse({'message': 'Введите действительный адрес электронной почты'}, status=400)

    email = form.cleaned_data.get('email')
    if NewsletterUser.objects.filter(email=email).exists():
        message = 'Ваш электронный адрес уже существует в нашей базе данных'
    else:
        message = 'Ваш адрес электронной почты был добавлен в нашу базу данных'

        subject = 'Спасибо за подписку на нашу рассылку'
        from_email = local_settings.DEFAULT_FROM_EMAIL
        to_email = [email]
        site = local_settings.SITES
        with open(local_settings.BASE_DIR + '/newsletter/templates/newsletter/user_email/sign_up_email.txt') as f:
            signup_message = f.read()
        messages_sub = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
        html_template = get_template('newsletter/user_email/sign_up_email.html').render()
        messages_sub.attach_alternative(html_template, 'text/html')

        '''Перехватываем ошибку при неверном email адресе. Если пользователь ввел несуществующий email адрес, то 
        выводим ему предупреждение 'Enter a valid email address' '''
        try:
            messages_sub.send()
            form.save()
        except SMTPDataError:
            return JsonResponse({'message': 'Введите действительный адрес электронной почты'}, status=400)

        '''Письмо админу о подписке на рассылку'''
        send_mail('Уважаемый админ сайта "{}" '.format(site),
                  'Адрес эл.почты {} был подписан на новостную рассылку!'.format(to_email), from_email, [from_email])

    return JsonResponse({'message': message}, status=201)


def newsletter_unsubscribe(request):
    '''Отписка от рассылки'''
    form = NewsletterUserSignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            NewsletterUser.objects.filter(email=instance.email).delete()
            messages.success(request, 'Ваш адрес электронной почты был удален')

            subject = 'Вы отписались от рассылки'
            from_email = local_settings.DEFAULT_FROM_EMAIL
            to_email = [instance.email]
            site = local_settings.SITES
            with open(local_settings.BASE_DIR + '/newsletter/templates/newsletter/user_email/unsubscribe_email.txt') as f:
                signup_message = f.read()
            message_un = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
            html_template = get_template('newsletter/user_email/unsubscribe_email.html').render()
            message_un.attach_alternative(html_template, 'text/html')
            message_un.send()

            '''Письмо админу об отписке на рассылку'''
            send_mail('Уважаемый админ сайта "{}" '.format(site),
                      'Адрес эл.почты {} был отписан от новостной рассылки.'.format(to_email), from_email, [from_email])

            return HttpResponseRedirect(request.path_info)

        else:
            messages.warning(request, 'Your email is not in the database')
            return HttpResponseRedirect(request.path_info)

    context = {
        'form': form,
    }

    return render(request, 'newsletter/unsubscribe.html', context)


@staff_member_required(login_url='https://google.com') # этот декоратор закрывает доступ к странице всех кроме superuser
def control_newsletter(request):
    '''Рассылка'''
    templates = Template.objects.filter(is_active=True)

    form = NewsletterCreationForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save()
        newsletter = Newsletter.objects.get(id=instance.id)
        if newsletter.status == Newsletter.EMAIL_STATUS_CHOICES.Published:
            subject = newsletter.subject
            body = newsletter.body
            from_email = local_settings.DEFAULT_FROM_EMAIL
            messages.success(request, 'Your messages have been sent successfully.')
            for email in newsletter.users_email.all():
                # send_mail(subject=subject, from_email=from_email, recipient_list=[email.email], message=body, fail_silently=True)
                mail = EmailMultiAlternatives(subject, body, from_email, [email.email])
                if newsletter.file:
                    mail.attach_file(instance.file.path)
                mail.content_subtype = 'html'
                mail.send(fail_silently=True)

            return HttpResponseRedirect(request.path_info)

        else:
            messages.warning(request, 'An error has occurred, please try sending a message later.')

    context = {
        'form': form,
        'templates': templates,
    }

    return render(request, 'newsletter/control_panel/control_newsletter.html', context)


def control_newsletter_list(request):
    '''Список всех рассылок'''
    newsletters = Newsletter.objects.all().order_by('-created')

    paginator = Paginator(newsletters, 20)
    page = request.GET.get('page')
    newsletters = paginator.get_page(page)

    context = {
        'newsletters': newsletters,
    }

    return render(request,'newsletter/control_panel/control_newsletter_list.html', context)


def control_newsletter_detail(request, pk):
    '''Детальный вывод рассылки'''
    newsletter = get_object_or_404(Newsletter, pk=pk)

    context = {
        'newsletter': newsletter
    }

    return render(request, 'newsletter/control_panel/control_newsletter_detail.html', context)


def control_newsletter_edit(request, pk):
    '''Редактирование рассылки'''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        form = NewsletterCreationForm(request.POST, instance=newsletter)
        if form.is_valid():
            newsletter = form.save()
            if newsletter.status == 'Published':
                subject = newsletter.subject
                body = newsletter.body
                from_email = local_settings.DEFAULT_FROM_EMAIL
                for email in newsletter.email.all():
                    send_mail(subject=subject, from_email=from_email, recipient_list=[email], message=body,
                              fail_silently=True)
            return redirect('newsletter:control_newsletter_detail', pk=newsletter.pk)

    else:
        form = NewsletterCreationForm(instance=newsletter)

    context = {
        'form': form
    }

    return render(request, 'newsletter/control_panel/control_newsletter.html', context)


def control_newsletter_delete(request, pk):
    '''Удаление рассылки'''
    newsletter = get_object_or_404(Newsletter, pk=pk)
    if request.method == 'POST':
        form = NewsletterCreationForm(request.POST, instance=newsletter)
        if form.is_valid():
            newsletter.delete()
            return redirect('newsletter:control_newsletter_list')
    else:
        form = NewsletterCreationForm(instance=newsletter)

    context = {
        'form': form
    }

    return render(request, 'newsletter/control_panel/control_newsletter_delete.html', context)


def control_newsletter_search(request):
    '''Поиск по рассылкам'''
    query = request.GET.get('q')

    '''Проверяем, если запрос был (http://localhost:8001/dashboard/search/) то выводим пустой кверисет'''
    if query:
        search_newsletter = Newsletter.objects.filter(
            Q(id__icontains=query)|
            Q(subject__icontains=query)|
            Q(body__icontains=query)|
            Q(status__icontains=query)|
            Q(created__icontains=query)

        )
    else:
        search_newsletter = Newsletter.objects.none()

    count_newsletter = search_newsletter.count()

    paginator = Paginator(search_newsletter, 10)
    page = request.GET.get('page')
    search_newsletter = paginator.get_page(page)

    context = {
        'search_newsletter': search_newsletter,
        'count_newsletter': count_newsletter,
        'query': query,

    }

    return render(request, 'newsletter/control_panel/control_newsletter_search.html', context)


def control_newsletter_templates(request):
    '''Товарный шаблон для рассылки'''
    templates = Template.objects.filter(is_active=True)

    context = {
        'templates': templates,
        'site_url': site_url,  # Подгружаем урл сайта из settings.py


    }

    return render(request, 'newsletter/control_panel/control_newsletter_templates.html', context)

newsletter/templates/newsletter/control_panel/control_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'shop/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'shop/css/dashboard.css' %}" rel="stylesheet">

     <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">Рассылки</a>
        </div>
        <div class="navbar-collapse collapse">
{#          <ul class="nav navbar-nav navbar-right">#}
{#            <li><a href="#">Dashboard</a></li>#}
{#            <li><a href="#">Settings</a></li>#}
{#            <li><a href="#">Profile</a></li>#}
{#            <li><a href="#">Help</a></li>#}
{#          </ul>#}
            <form class="navbar-form" role="search" action="{% url 'newsletter:control_newsletter_search' %}" method="get" style="text-align: center">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Поиск" name="q">
                </div>
                <button type="submit" class="btn btn-default">Отправить</button>
            </form>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class=""><a href="{% url 'newsletter:control_newsletter' %}">Рассылки</a></li>
{#            <li><a href="#">Reports</a></li>#}
{#            <li><a href="#">Analytics</a></li>#}
{#            <li><a href="#">Export</a></li>#}
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'newsletter:control_newsletter_list' %}">Список рассылок</a></li>
{#            <li><a href="">Nav item again</a></li>#}
{#            <li><a href="">One more nav</a></li>#}
{#            <li><a href="">Another nav item</a></li>#}
{#            <li><a href="">More navigation</a></li>#}

          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'newsletter:control_newsletter_templates' %}" target="_blank">Шаблон рассылок</a></li>
{#            <li><a href="">One more nav</a></li>#}
{#            <li><a href="">Another nav item</a></li>#}
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block content %}

            {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'shop/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'shop/js/bootstrap.min.js' %}"></script>

  <!-- тег из шаблона control_newsletter.html -->
  {% block extra_js %}{% endblock %}

  </body>
</html>

newsletter/templates/newsletter/control_panel/control_newsletter_delete.html
{% extends 'newsletter/control_panel/control_base.html' %}
{% load bootstrap3 %}

{% block content %}

    <h1 class="page-header">Удаление рассылки</h1>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

    <input type="button" value="Выделить все" onclick="check(this.form.users_email,1)">
    <input type="button" value="Снять выделение" onclick="check(this.form.users_email,0)">
    <br><br>

    <button class="btn btn-danger" type="submit">Удалить</button>
    </form>

    <!-- Выделить/Снять выделение чекбоксов -->
    <script type="text/javascript">
        function check(field, flag) {
            if (flag == "1") {
                for (i = 0; i < field.length; i++) {
                    field[i].checked = true;
                }
            } else {
                for (i = 0; i < field.length; i++) {
                    field[i].checked = false;
                }
            }
        }
    </script>

{% endblock %}

newsletter/templates/newsletter/control_panel/control_newsletter_detail.html
{% extends 'newsletter/control_panel/control_base.html' %}
{% load bootstrap3 %}



{% block content %}


    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="width: 100%; margin-left: -1%;">
        <div class="page-header">
            <h1 style="margin-left: 25%;">{{ newsletter.subject }}</h1>
        </div>
        {{ newsletter.body|safe }}
        <br>
        <div class="col-sm-8 col-sm-offset-4">
            <div class="col-sm-2"><a href="{% url 'newsletter:control_newsletter_edit' pk=newsletter.pk %}"><button class="btn btn-warning">Изменить</button></a></div>
            <div class="col-sm-2"><a href="{% url 'newsletter:control_newsletter_delete' pk=newsletter.pk %}"><button class="btn btn-danger">Удалить</button></a></div>
            <div class="col-sm-2"><a href="{% url 'newsletter:control_newsletter' %}"><button class="btn btn-success">Новая рассылка</button></a></div>
        </div>
    </div>



{% endblock %}

newsletter/templates/newsletter/control_panel/control_newsletter_list.html
{% extends 'newsletter/control_panel/control_base.html' %}
{% load bootstrap3 %}

{% block content %}


    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main" style="width: 100%; margin-left: -1%;">
        <div class="row">
            <div class="col-sm-10">
                <h1 class="page-header">Список рассылок</h1>
            </div>
            <div class="col-sm-2">
                <a href="{% url 'newsletter:control_newsletter' %}"><button type="button" class="btn-success">Новая рассылка</button></a>
            </div>
        </div>
        {% if newsletters %}
        <div class="table-responsive table-hover">
            <table class="table table-hover">
                <thead>
                    <th>id</th>
                    <th>Тема</th>
                    <th>Статус</th>
                    <th>Создана</th>
                    <th>Обновлена</th>
                    <th>Изменить</th>
                    <th>Удалить</th>
                </thead>
                <tbody>
                {% for item in newsletters %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td><a href="{% url 'newsletter:control_newsletter_detail' pk=item.pk %}">{{ item.subject }}</a></td>
                        <td>{{ item.get_status_display }}</td>
                        <td>{{ item.created }}</td>
                        <td>{{ item.updated }}</td>
                        <td><a href="{% url 'newsletter:control_newsletter_edit' pk=item.pk %}"><button class="btn btn-warning">Изменить</button></a></td>
                        <td><a href="{% url 'newsletter:control_newsletter_delete' pk=item.pk %}"><button class="btn btn-danger">Удалить</button></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
            {% else %}
            <h2>У вас пока нет рассылок.</h2>
        {% endif %}
            <!-- Пагинация -->
        <div class="pagination-area">
            <div class="pagination">
                <ul>
                    {% bootstrap_pagination newsletters pages_to_show=3 %}<br>
                    <span>Показано с 1 по {{ newsletters.number }} из ({{ newsletters.paginator.num_pages }} Страниц)</span>
                </ul>
            </div>
        </div>

    </div>

{% endblock %}

newsletter/templates/newsletter/control_panel/control_newsletter_search.html
{% extends 'newsletter/control_panel/control_base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}


{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="row">
            <div class="col-sm-10">
                <h1 class="page-header">Результат поиска по рассылкам</h1>
            </div>
        </div>

        <h2>{% if search_newsletter %}По запросу "{{ query }}" найдено {{ count_newsletter }} результатов. {% else %}По запросу "{{ query }}" ничего не найдено.{% endif %}</h2><br><br>

        {% if search_newsletter %}
        <div class="table-responsive table-hover">
            <table class="table table-hover">
                <thead>
                    <th>id</th>
                    <th>Тема</th>
                    <th>Статус</th>
                    <th>Создана</th>
                    <th>Обновлена</th>
                    <th>Редактировать</th>
                    <th>Удалить</th>
                </thead>
                <tbody>
                    {% for newsletter in search_newsletter %}
                    <tr>
                        <td>{{ newsletter.id|safe }}</td>
                        <td><a href="{% url 'newsletter:control_newsletter_detail' pk=newsletter.pk %}">{{ newsletter.subject|safe }}</a></td>
                        <td>{{ newsletter.get_status_display }}</td>
                        <td>{{ newsletter.created }}</td>
                        <td>{{ newsletter.updated }}</td>
                        <td><a href="{% url 'newsletter:control_newsletter_edit' pk=newsletter.pk %}"><button class="btn btn-warning">Редактировать</button></a></td>
                        <td><a href="{% url 'newsletter:control_newsletter_delete' pk=newsletter.pk %}"><button class="btn btn-danger">Удалить</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
            <!-- Пагинация -->
        <div class="pagination-area">
            <div class="row">
                <div class="col-xs-5">
                    <div class="pagination">
                        <ul>
                            {% bootstrap_pagination search_newsletter extra=request.GET.urlencode pages_to_show=3 %} <br>
                            <span>Показано с 1 по {{ search_newsletter.number }} из ({{ search_newsletter.paginator.num_pages }} Страниц)</span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock %}